- name: Generate the sitemap
  if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
  id: sitemap
  uses: cicirello/generate-sitemap@v1
  with:
    base-url-path: https://bitbadges.org/
    path-to-root: gh-pages
- name: Output stats
  if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
  run: |
    echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
    echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
    echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
- name: Commit website sitemap
  if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
  run: |
    cd gh-pages
    if [[ `git status --porcelain` ]]; then
      git config --global user.name 'github-actions'
      git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      git add -A
      git commit -m "sitemap update."
    fi
    git push
    cd ..
